### ISSUE TITLE
Unable to invoke Swift examples

### ISSUE THREAD

**Issue by leopic** [aws-samples/sessions-with-aws-sam#2] opened 2020-07-19 21:43 UTC
Thank you for putting this repo together, I'm an iOS Developer that had my eye on working with the custom Swift runtime when it became available.

On to the issue, I am unable to run either of the lambdas, this the error for both of them:
```bash
➜  swift-custom-runtime git:(master) sam local invoke Squared -e events/sqaured-event.json
Invoking swift.bootstrap (provided)

Fetching lambci/lambda:provided Docker container image......
Mounting /Users/leo/Sites/aws-swift-lambda/sessions-with-aws-sam/swift-custom-runtime as /var/task:ro,delegated inside runtime container
START RequestId: 7e406ac6-09c0-1fcb-d682-753a6fe75e28 Version: $LATEST
END RequestId: 7e406ac6-09c0-1fcb-d682-753a6fe75e28
REPORT RequestId: 7e406ac6-09c0-1fcb-d682-753a6fe75e28	Init Duration: 24.25 ms	Duration: 1.34 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 7 MB

{"errorType":"exitError","errorMessage":"RequestId: 7e406ac6-09c0-1fcb-d682-753a6fe75e28 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}

---

➜  swift-custom-runtime git:(master) sam local invoke SwiftApi -e events/api-event.json
Invoking swift.bootstrap (provided)

Fetching lambci/lambda:provided Docker container image......
Mounting /Users/leo/Sites/aws-swift-lambda/sessions-with-aws-sam/swift-custom-runtime as /var/task:ro,delegated inside runtime container
START RequestId: 1d33feac-9719-10a0-a269-bdc6a1094ce9 Version: $LATEST
END RequestId: 1d33feac-9719-10a0-a269-bdc6a1094ce9
REPORT RequestId: 1d33feac-9719-10a0-a269-bdc6a1094ce9	Init Duration: 20.96 ms	Duration: 0.74 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 7 MB

{"errorType":"exitError","errorMessage":"RequestId: 1d33feac-9719-10a0-a269-bdc6a1094ce9 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}
````

Using:
- Docker version 19.03.8, build afacb8b
- SAM CLI, version 0.53.0
- macOS Catalina 10.15.5

FWIW: the Squared example also fails to run in AWS with a similar error:
```
START RequestId: 83e1552b-8157-42e3-a57c-b0d4184bed91 Version: $LATEST
END RequestId: 83e1552b-8157-42e3-a57c-b0d4184bed91
REPORT RequestId: 83e1552b-8157-42e3-a57c-b0d4184bed91	Duration: 26.78 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 5 MB	
RequestId: 83e1552b-8157-42e3-a57c-b0d4184bed91 Error: &{0xc0000cc070 map[error:Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] invoke_id:83e1552b-8157-42e3-a57c-b0d4184bed91 sandbox_id:0] 2020-07-19 21:47:23.284976935 +0000 UTC m=+0.007731215 panic <nil> Failed to locate runtime bootstrap <nil> <nil> }
Runtime.ExitError
```

**Comment by singledigit** [comment] 2020-08-05 00:05
@leopic thanks for the notice. I believe the problem is if you use the make commands without doing sam build at least one time. Sam updates and copies the template file to the .aws-sam build directory and is then referenced by sam local. Can you try running `sam build` one time, then you can run make build-<function> subsequently.

**Comment by singledigit** [comment] 2020-09-15 17:51
Closing for now

**Closed by singledigit** 2020-09-15 17:51 UTC
